apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: swift-iguana-go 
  janus-idp.io/tekton: swift-iguana-go
  backstage.io/kubernetes-id: swift-iguana-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: swift-iguana-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  