apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: swift-iguana-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: swift-iguana-go 
  name: swift-iguana-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: swift-iguana-go 
